all: SLList_ints DLList_ints

SLList_ints: SLList_ints.c
	clang -std=c99 -g -o SLList_ints_test SLList_ints.c test_SLList_ints.c

DLList_ints: DLList_ints.c
	clang -std=c99 -g -o DLList_ints_test DLList_ints.c test_DLList_ints.c
